# hBN PBEsol 12x12x1 defect supercell — boron vacancy VB-

phonopy:
  dim: "1 1 1"
start_from_supercell: true
compute_mode: "sbatch_mix"

compute_modes:
  sbatch_mix:
    sbatch_relax: "--nodes=8 --gpus-per-node=4 --ntasks-per-node=4 --cpus-per-task=32 --time=01:00:00 --qos=regular --constraint=gpu -A m526"
    srun_relax: "--cpu_bind=cores --gpus-per-node=4 --ntasks-per-node=4 --nodes=16 --cpus-per-task=32 -C gpu"
    srun_per_dir: "--cpu_bind=cores --gpus-per-node=1 --ntasks-per-node=1 --nodes=1 --cpus-per-task=64 -C gpu"
    srun_cpu_relax: "--cpu_bind=cores --nodes=1 --ntasks=16 --cpus-per-task=4"
    sbatch: "--nodes=192 --gpus-per-node=4 --ntasks-per-node=4 --cpus-per-task=32 --time=04:00:00 --qos=regular --constraint=gpu -A m526"

steps:
  defect_relax_1:
    kpoints: {mesh: "1 1 1"}
    incar_overrides: |
      NELECT = 1150
      GGA = PS
      ENCUT = 400
      KPAR = 1
  hf_setup: {}
  force_consts:
    kpoints: {mesh: "1 1 1"}
    incar_overrides: |
      NELECT = 1150
      GGA = PS
      ENCUT = 400
      KPAR = 1
  phonon_post: {}

  
# raman_prep: {}
# resonant_vasp:
#   kpoints: {mesh: "1 1 1"}
#   incar_overrides: |
#     ENCUT = 400
#     NELECT = 1150
#     GGA = PS
#     NBANDS = 1728
#     KPAR = 1
# post_process: {}
  


#defect_relax_2_cpu:
# kpoints: {mesh: "1 1 1"}
# incar_overrides: |
#   NELECT = 1150
#   GGA = PS
#   ISIF = 4
#   ALGO = Normal
#   ENCUT = 400