#!/usr/bin/env python3
"""Plot primitive in-plane lattice constants for all simulations.

Reads lattice_constants.csv from ~/post/<material>/ (generated by compile_phonon_data.py).
Groups bars by simulation type (Pristine / V_B- / V_B0) with paired colours per functional.

Usage:
    plot_lattice_constants.py [--out <path>]

    --out <path>   Output PNG path (default: ~/post/lattice_constants_comparison.png)
"""

import csv
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_RAMAN_ROOT = os.path.dirname(os.path.dirname(_HERE))
if _RAMAN_ROOT not in sys.path:
    sys.path.insert(0, _RAMAN_ROOT)

STYLE_FILE = os.path.join(_HERE, "raman.mplstyle")
POST_DIR   = os.path.expanduser("~/post")

# Dark / light colour pairs per functional
PALETTE = {
    "CA": ("#1565C0", "#90CAF9"),  # LDA  — blue
    "PE": ("#B71C1C", "#EF9A9A"),  # PBE  — red
    "PS": ("#1B5E20", "#A5D6A7"),  # PBEsol — green
}

# (material_name, x_tick_label, functional_GGA)
LAYOUT = [
    ("Pristine", [
        ("hBN_LDA",          "LDA",           "CA"),
        ("hBN_PBE",          "PBE",           "PE"),
        ("hBN_PBEsol_6x6x1", "PBEsol",        "PS"),
    ]),
    ("V_B- (286)", [
        ("hBN_PBEsol_defect",       "PBEsol",         "PS"),
        ("hBN_PBEsol_defect_opt",   "PBEsol (opt)",   "PS"),
        ("hBN_PBEsol_defect_fixed", "PBEsol (fixed)", "PS"),
        ("hBN_LDA_defect",          "LDA",            "CA"),
        ("hBN_LDA_defect_fixed",    "LDA (fixed)",    "CA"),
        ("hBN_PBE_defect",          "PBE",            "PE"),
        ("hBN_PBE_defect_fixed",    "PBE (fixed)",    "PE"),
    ]),
    ("V_B0 (285)", [
        ("hBN_PBEsol_defect_neutral",       "PBEsol",         "PS"),
        ("hBN_PBEsol_defect_neutral_fixed", "PBEsol (fixed)", "PS"),
    ]),
]


def load_a(name):
    p = os.path.join(POST_DIR, name, "lattice_constants.csv")
    if not os.path.isfile(p):
        raise FileNotFoundError(
            f"~/post/{name}/lattice_constants.csv not found — "
            f"run compile_phonon_data.py {name} first"
        )
    with open(p) as f:
        return float(list(csv.DictReader(f))[0]["a_primitive_Ang"])


def bar_color(name, gga):
    dark, light = PALETTE[gga]
    if name.endswith("_fixed"):
        return light
    if name.endswith("_opt"):
        r = lambda h: int(h[1:3], 16)
        g = lambda h: int(h[3:5], 16)
        b = lambda h: int(h[5:7], 16)
        return "#{:02x}{:02x}{:02x}".format(
            (r(dark) + r(light)) // 2,
            (g(dark) + g(light)) // 2,
            (b(dark) + b(light)) // 2,
        )
    return dark


def plot(out_path):
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt
    import matplotlib.ticker
    from matplotlib.patches import Patch
    from matplotlib.lines import Line2D

    if os.path.isfile(STYLE_FILE):
        plt.style.use(STYLE_FILE)
    matplotlib.rcParams["text.usetex"] = False

    bar_width, gap_inner, gap_group = 0.5, 0.08, 0.7
    fig, ax = plt.subplots(figsize=(12, 4))
    fig.subplots_adjust(bottom=0.28, left=0.08, right=0.98, top=0.93)

    xticks, xlabels, all_a = [], [], []
    group_spans = []
    x = 0.0

    for group_label, entries in LAYOUT:
        group_start = x
        for name, tick_label, gga in entries:
            a = load_a(name)
            all_a.append(a)
            ax.bar(x, a, width=bar_width, color=bar_color(name, gga),
                   edgecolor="none", zorder=3)
            xticks.append(x)
            xlabels.append(tick_label)
            x += bar_width + gap_inner
        group_spans.append((group_label, group_start, x - gap_inner))
        x += gap_group

    y_min, y_max = min(all_a) - 0.003, max(all_a) + 0.003
    x_max = x - gap_group + 0.3

    # Subtle vertical dividers between groups
    for _, _, g_end in group_spans[:-1]:
        ax.axvline(g_end + gap_group / 2, color="0.75", lw=0.5, ls="--", zorder=1)

    # Group labels as a bracket row below x-axis
    bracket_y = y_min - (y_max - y_min) * 0.38
    tick_y    = y_min - (y_max - y_min) * 0.20
    for group_label, g_start, g_end in group_spans:
        mid = (g_start + g_end) / 2
        # Bracket lines
        for xb in (g_start - bar_width * 0.3, g_end + bar_width * 0.3):
            ax.plot([xb, xb], [bracket_y, tick_y], color="0.4", lw=0.6,
                    clip_on=False, transform=ax.transData)
        ax.plot([g_start - bar_width * 0.3, g_end + bar_width * 0.3],
                [bracket_y, bracket_y], color="0.4", lw=0.6,
                clip_on=False, transform=ax.transData)
        ax.text(mid, bracket_y - (y_max - y_min) * 0.05, group_label,
                ha="center", va="top", fontsize=8.5, clip_on=False)

    ax.set_xticks(xticks)
    ax.set_xticklabels(xlabels, rotation=35, ha="right", fontsize=7.5)
    ax.set_ylabel("a (Å)")
    ax.set_ylim(y_min, y_max)
    ax.set_xlim(-0.4, x_max)
    ax.yaxis.set_major_formatter(matplotlib.ticker.FormatStrFormatter("%.4f"))
    ax.yaxis.set_minor_locator(matplotlib.ticker.AutoMinorLocator())
    ax.tick_params(bottom=False)  # remove x ticks, labels are enough
    ax.spines["top"].set_visible(False)
    ax.spines["right"].set_visible(False)

    # Legend: functional colours + shade meaning
    legend_elements = [
        Patch(facecolor=PALETTE["PS"][0], edgecolor="none", label="PBEsol"),
        Patch(facecolor=PALETTE["CA"][0], edgecolor="none", label="LDA"),
        Patch(facecolor=PALETTE["PE"][0], edgecolor="none", label="PBE"),
        Line2D([], [], color="none", label=""),  # spacer
        Patch(facecolor="0.25", edgecolor="none", label="Fully relaxed"),
        Patch(facecolor="0.60", edgecolor="none", label="CPU opt"),
        Patch(facecolor="0.82", edgecolor="none", label="Fixed lattice"),
    ]
    ax.legend(handles=legend_elements, fontsize=7.5, loc="upper right",
              ncol=2, columnspacing=0.8, handlelength=1.2, handletextpad=0.5)

    fig.savefig(out_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Plot -> {out_path}")


def main():
    args = sys.argv[1:]
    out_path = os.path.expanduser("~/post/lattice_constants_comparison.png")
    i = 0
    while i < len(args):
        if args[i] == "--out" and i + 1 < len(args):
            out_path = args[i + 1]; i += 2
        else:
            print(f"Unknown argument: {args[i]}"); sys.exit(1)
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    plot(out_path)


if __name__ == "__main__":
    main()
