# hBN PBE defect supercell — boron vacancy

phonopy:
  dim: "1 1 1"
start_from_supercell: true
compute_mode: "interactive_serial"

compute_modes:
  interactive_serial:
    srun_relax: "--cpu_bind=cores --gpus-per-node=3 --ntasks-per-node=3 --nodes=4 --cpus-per-task=32 -C gpu"
    srun_cpu_relax: "--cpu_bind=cores --nodes=4 --ntasks-per-node=16 --cpus-per-task=4"
    salloc: "-N 4 -C gpu --gpus-per-node=3 -t 04:00:00 --qos=interactive -A m526"

seed_files:
  chgcar: /pscratch/sd/e/easuresh/vasp_calculations/hBN_PBEsol_6x6x1/hf/groundstate/CHGCAR
  wavecar: /pscratch/sd/e/easuresh/vasp_calculations/hBN_PBEsol_6x6x1/hf/groundstate/WAVECAR

steps:
  defect_relax_1:
    kpoints: {mesh: "4 4 1"}
    incar_overrides: |
      NELECT = 286
      GGA = PE
  defect_relax_2_cpu:
    kpoints: {mesh: "4 4 1"}
    incar_overrides: |
      NELECT = 286
      GGA = PE
      ISIF = 4
      ALGO = Normal
  hf_setup: {}
  force_consts:
    kpoints: {mesh: "4 4 1"}
    incar_overrides: |
      NELECT = 286
      GGA = PE
  phonon_post: {}
