"""Phonopy-related utilities: config files, eigenvectors."""

import os


def ensure_dim_in_conf(conf_path, label, dim):
    """Ensure a phonopy .conf file exists with DIM + default IRREPS setting.

    Preserves any existing content (just prepends DIM) — this file may have
    other phonopy settings worth keeping, so it's never blindly overwritten.
    """
    if os.path.exists(conf_path):
        with open(conf_path) as f:
            content = f.read()
        if "DIM" in content:
            return
        print(f"  [setup] {label} lacks DIM — prepending DIM = {dim}...")
    else:
        print(f"  [setup] {label} not found — creating with DIM = {dim} + IRREPS = 0 0 0...")
        content = "IRREPS = 0 0 0\n"
    with open(conf_path, "w") as f:
        f.write(f"DIM = {dim}\n{content}")


def write_eigenvectors_conf(path, dim, band_path, band_labels, band_points):
    """Create or update *path* as a phonopy eigenvectors.conf file.

    Always auto-generated (no user customization to preserve), so this just
    compares against the expected content and rewrites if anything differs —
    one check instead of three, and it catches any drift, not just the
    specific tags the old per-tag checks happened to look for.
    """
    lines = ["# eigenvectors.conf — auto-generated by automation_raman_analysis.py",
             f"DIM = {dim}", f"BAND = {band_path}"]
    if band_labels:
        lines.append(f"BAND_LABELS = {band_labels}")
    lines.append(f"BAND_POINTS = {band_points}")
    lines.append("EIGENVECTORS = .TRUE.")
    expected = "\n".join(lines) + "\n"

    if os.path.exists(path):
        with open(path) as f:
            if f.read() == expected:
                return False
        print("  [9b] eigenvectors.conf changed — regenerating...")
    else:
        print("  [9b] eigenvectors.conf not found — creating...")
    with open(path, "w") as f:
        f.write(expected)
    return True
