"""Phonopy-related utilities: config files, eigenvectors."""

import os


def ensure_dim_in_conf(conf_path, label, dim):
    """Ensure a phonopy .conf file exists with DIM + default IRREPS setting."""
    if not os.path.exists(conf_path):
        print(f"  [setup] {label} not found — creating with DIM = {dim} + IRREPS = 0 0 0...")
        with open(conf_path, "w") as f:
            f.write(f"DIM = {dim}\n")
            f.write("IRREPS = 0 0 0\n")
        return True
    with open(conf_path) as f:
        content = f.read()
    if "DIM" not in content:
        print(f"  [setup] {label} lacks DIM — prepending DIM = {dim}...")
        with open(conf_path, "w") as f:
            f.write(f"DIM = {dim}\n")
            f.write(content)
    return True


def write_eigenvectors_conf(path, dim, band_path, band_labels, band_points):
    """Create or update *path* as a phonopy eigenvectors.conf file."""
    expected_band = f"BAND = {band_path}"
    needs_recreation = False
    if os.path.exists(path):
        with open(path) as f:
            content = f.read()
        if "DIM" not in content:
            needs_recreation = True
            print("  [9b] eigenvectors.conf exists but lacks DIM — regenerating...")
        elif expected_band not in content:
            needs_recreation = True
            print(f"  [9b] eigenvectors.conf BAND has changed — regenerating...")
        elif "BAND_POINTS" not in content:
            needs_recreation = True
            print("  [9b] eigenvectors.conf lacks BAND_POINTS — regenerating...")
    else:
        needs_recreation = True
        print("  [9b] eigenvectors.conf not found — creating...")

    if needs_recreation:
        with open(path, "w") as f:
            f.write("# eigenvectors.conf — auto-generated by automation_raman_analysis.py\n")
            f.write(f"DIM = {dim}\n")
            f.write(f"BAND = {band_path}\n")
            if band_labels:
                f.write(f"BAND_LABELS = {band_labels}\n")
            f.write(f"BAND_POINTS = {band_points}\n")
            f.write("EIGENVECTORS = .TRUE.\n")

    return needs_recreation
