"""Raman post-processing utilities."""

import os
import re

from .io import run_command


def generate_kopia_script(raman_dir, ra_dirs):
    """Write and execute the kopia script that copies vasprun.xml files into AXML/.

    Real copies, not symlinks: the cp pulls each vasprun.xml through the node's
    page cache right before genRAram610_dynamic parses it, which measured ~6x
    faster per energy than cold Lustre reads through symlinks. Files already
    copied (regular file, not a leftover symlink from the symlink-era kopia)
    are skipped, so retries of post_process don't re-pay the multi-GB copy.
    """
    kopia_path = os.path.join(raman_dir, "kopia")
    with open(kopia_path, "w") as kf:
        kf.write("#!/bin/bash\n")
        kf.write("# Dynamically generated by automation_raman_analysis.py\n")
        kf.write("mkdir -p AXML\n")
        for d in ra_dirs:
            dirname = os.path.basename(d)
            xml_name = dirname[len("ra_pos_"):] if dirname.startswith("ra_pos_") else dirname
            src = f"{dirname}/vasprun.xml"
            dst = f"AXML/{xml_name}.xml"
            kf.write(f'{{ [ -f "{dst}" ] && [ ! -L "{dst}" ]; }} || '
                     f'cp --remove-destination "{src}" "{dst}"\n')
    run_command(f"chmod +x kopia && ./kopia", cwd=raman_dir)


def inject_ramfile_energies(template_path, dst_path, energies):
    """Inject custom laser energies into ramfile_dynamic.sh."""
    with open(template_path) as f:
        template = f.read()
    energies_str = " ".join(f'"{e}"' for e in energies)
    match = re.search(r'^desired_energies=\([^)]*\)', template, re.MULTILINE)
    if not match:
        raise RuntimeError(
            "ramfile_dynamic.sh does not contain the expected "
            "'desired_energies=(...)' line — cannot inject custom energies."
        )
    content = template.replace(match.group(0), f"desired_energies=({energies_str})")
    with open(dst_path, "w") as f:
        f.write(content)
    os.chmod(dst_path, 0o755)
    print(f"  [setup] Generated {os.path.basename(dst_path)} with energies: {energies_str}")
