"""Raman post-processing utilities."""

import os
import re

from .io import run_command


def generate_kopia_script(raman_dir, ra_dirs):
    """Write and execute the kopia script that copies vasprun.xml files to AXML/."""
    kopia_path = os.path.join(raman_dir, "kopia")
    with open(kopia_path, "w") as kf:
        kf.write("#!/bin/bash\n")
        kf.write("# Dynamically generated by automation_raman_analysis.py\n")
        kf.write("mkdir -p AXML\n")
        for d in ra_dirs:
            dirname = os.path.basename(d)
            xml_name = dirname[len("ra_pos_"):] if dirname.startswith("ra_pos_") else dirname
            kf.write(f'cp "{dirname}/vasprun.xml" "AXML/{xml_name}.xml"\n')
    run_command(f"chmod +x kopia && ./kopia", cwd=raman_dir)


def inject_ramfile_energies(template_path, dst_path, energies):
    """Inject custom laser energies into ramfile_dynamic.sh."""
    with open(template_path) as f:
        template = f.read()
    energies_str = " ".join(f'"{e}"' for e in energies)
    match = re.search(r'^desired_energies=\([^)]*\)', template, re.MULTILINE)
    if not match:
        raise RuntimeError(
            "ramfile_dynamic.sh does not contain the expected "
            "'desired_energies=(...)' line — cannot inject custom energies."
        )
    content = template.replace(match.group(0), f"desired_energies=({energies_str})")
    with open(dst_path, "w") as f:
        f.write(content)
    os.chmod(dst_path, 0o755)
    print(f"  [setup] Generated {os.path.basename(dst_path)} with energies: {energies_str}")
